### ISSUE TITLE
change on the debian-security path files

### ISSUE THREAD

**Issue by Yazaeld** [mrlesmithjr/ansible-apt-sources#9]
**Describe the bug**
Update impossible for debian-security : security/stable does not have a release file

**To Reproduce**
apt-get update on a debian distribution

**Expected behavior**

**Desktop (please complete the following information):**
 - OS: Debian
 - Version  10

**Comment by Yazaeld** [comment]
@mrlesmithjr is it possible to tag a version ? Since changes are automatically merge in master branch i'd prefer to have a stable version. Thanks :)

**Comment by mrlesmithjr** [comment]
Done
